"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['orQanon.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'includes': ['sip', 'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets', 'pyaudio', 'matplotlib',
                        'scipy', 'numpy'],
           'qt_plugins': ['platforms/*', 'imageformats/*'],
           'excludes': ['PyQt5.QtWebKit', 'PyQt5.QtWebKitWidgets',
                        'PyQt5.QtDesigner', 'PyQt5.QtXmlPatterns', 'PyQt5.QtQml',
                        'PyQt5.QtQuick', 'PyQt5.QtDeclarative'],
           'iconfile': 'rsrc/icon.icns',
           'dylib_excludes': ['QtWebKit.framework', 'QtWebKitWidgets.framework',
                              'QtDesigner.framework', 'QtXmlPatterns.framework', 'QtQml.framework',
                              'QtQuick.framework', 'QtDeclarative'],
           'plist': {
               'CFBundleShortVersionString': '1.0',
               'CFBundleGetInfoString': 'orQanon GUI'}
}

setup(
    app=APP,
    version='0.0.1',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    # py_modules=['orQanon_mainWindow', 'orQanon_ui', 'synth']
)
